spring:
  application:
    name: spring-cloud-server
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}
  instance:
    preferIpAddress: true
